agent_class: DQN
total_timesteps: 1e5
n_eval_episodes: 5
policy_model: MlpPolicy
model_kwargs:
  learning_rate: 0.0001
  batch_size: 32
  tau: 1.0
  gamma: 0.99
  learning_starts: 50000
  train_freq: 4
  gradient_steps: 1
  exploration_fraction: 0.1
  exploration_initial_eps: 1.0
  exploration_final_eps: 0.05
  buffer_size: 1000000
