defaults:
  - algorithm: ppo
  - search_space: ppo
  - override hydra/sweeper: DEHB
  - override hydra/launcher: submitit_local

hydra:
#  launcher:
#    partition: cpu_short
#    cpus_per_task: 1
#    mem_gb: 1
#    gres: null
#    timeout_min: 10
  sweeper:
    dehb_kwargs:
      mutation_factor: 0.2
      max_budget: ${algorithm.total_timesteps}
      min_budget: 1e3
      deepcave: true
    search_space: ${search_space}
    total_brackets: 3
    budget_variable: algorithm.total_timesteps
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}

env_name: Pendulum-v1
load: false
save: false
reward_curves: false
seed: 0
